import { TeamMember, NewsArticle, Vacancy, ResearchObjective, AdminUser, ActivityLog, Tool } from '@/types';

export const INITIAL_USERS: AdminUser[] = [
  {
    id: 'a0000000-0000-0000-0000-000000000003',
    name: 'Miskatul Anwar',
    username: 'miskat',
    email: 'miskat.cse@cu.ac.bd',
    role: 'Admin',
    avatar: '/team/miskat.jpg',
    status: 'active',
    department: 'Department of CSE, University of Chittagong',
    createdAt: '2025-01-10',
  },
];

export const DEMO_ADMIN_USER: AdminUser = INITIAL_USERS[0];

export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
  // SPM Team
  {
    id: 'team_rpdn',
    name: 'Prof. Dr. Rudra Pratap Deb Nath',
    designation: 'SPM',
    category: 'SPM Team',
    institution: 'University of Chittagong',
    email: 'rudra@cu.ac.bd',
    bio: 'Professor, Department of CSE. Director of BIKE Lab. Expert in Knowledge Graphs, Semantic Web, and Data Science. Principal investigator for HEAT-13211-CU ATF.',
    image: '/team/rpdn.png',
    scholarUrl: 'https://scholar.google.com/citations?user=TkQGAWoAAAAJ',
    order: 1,
  },
  {
    id: 'team_anc',
    name: 'Dr. Abu Nowshed Chy',
    designation: 'ASPM',
    category: 'SPM Team',
    institution: 'University of Chittagong',
    email: 'nowshed@cu.ac.bd',
    bio: 'Assistant Professor, Department of CSE. Specialized in Natural Language Processing, Deep Learning, and AI reasoning systems.',
    image: '/team/anc.png',
    scholarUrl: 'https://scholar.google.com/citations?user=hQuUosgAAAAJ',
    order: 2,
  },
  {
    id: 'team_mmi',
    name: 'Dr. Md. Mahbubul Islam',
    designation: 'Associate Professor',
    category: 'SPM Team',
    institution: 'University of Chittagong',
    email: 'mahbubcse@cu.ac.bd',
    bio: 'Associate Professor, South Korea PhD. Specializes in Computer Vision, Machine Learning, and multimodal representations.',
    image: '/team/mmi.png',
    scholarUrl: 'https://scholar.google.com',
    order: 3,
  },
  {
    id: 'team_sc',
    name: 'Shima Chakraborty',
    designation: 'Assistant Professor',
    category: 'SPM Team',
    institution: 'University of Chittagong',
    email: 'shimacse@cu.ac.bd',
    bio: 'Assistant Professor, Department of CSE. Specializes in Semantic Web, Ontology Engineering, and Data Science.',
    image: '/team/sc.png',
    scholarUrl: 'https://scholar.google.com',
    order: 4,
  },

  // Student Researchers
  {
    id: 'team_nesarul',
    name: 'Md. Nesarul Haque',
    designation: 'PhD Fellow',
    category: 'Student Researchers',
    institution: 'Dept. of CSE, University of Chittagong',
    email: 'nesarul@std.cu.ac.bd',
    bio: 'PhD candidate researching AI security, social media analysis, and cyberbullying detection over graph models.',
    image: '/team/nesarul.jpg',
    order: 5,
  },
  {
    id: 'team_noortaz',
    name: 'Noortaz Rezwana',
    designation: 'PhD Fellow',
    category: 'Student Researchers',
    institution: 'Dept. of CSE, University of Chittagong',
    email: 'noortaz@std.cu.ac.bd',
    bio: 'PhD fellow investigating knowledge graph construction and reasoning over biomedical data.',
    image: '/team/noor.jpg',
    order: 6,
  },
  {
    id: 'team_atik',
    name: 'Atik Ishrak',
    designation: 'Research Assistant',
    category: 'Student Researchers',
    institution: 'Dept. of CSE, University of Chittagong',
    email: 'atikishrak66@gmail.com',
    bio: 'Undergraduate researcher working on data pipelines, knowledge extraction, and LLM benchmarking.',
    image: '/team/atikishrak.jpg',
    order: 7,
  },
  {
    id: 'team_kais',
    name: 'Md. Kais',
    designation: 'Research Assistant',
    category: 'Student Researchers',
    institution: 'Dept. of CSE, University of Chittagong',
    email: 'mdkais3@gmail.com',
    bio: 'Research Assistant focusing on graph querying, vector databases, and retrieval augmented generation.',
    image: '/team/kais.jpg',
    order: 8,
  },
  {
    id: 'team_raihan',
    name: 'Md Raihan Kabir Rifat',
    designation: 'Masters Fellow',
    category: 'Student Researchers',
    institution: 'Dept. of CSE, University of Chittagong',
    email: 'raihankabir@std.cu.ac.bd',
    bio: 'Masters fellow working on open data quality frameworks and semantic data ecosystems.',
    image: '/team/raihan.jpg',
    order: 9,
  },

  // Data Annotators & Staff
  {
    id: 'team_miskat',
    name: 'Miskatul Anwar',
    designation: 'Data Annotator & Developer',
    category: 'Data Annotators',
    institution: 'Dept. of CSE, University of Chittagong',
    email: 'miskat@std.cu.ac.bd',
    bio: 'Student at CSE CU. Leading frontend engineering, administrative dashboard tooling, and data curation.',
    image: '/team/miskat.jpg',
    order: 10,
  },
  {
    id: 'team_minhaj',
    name: 'Minhajul Islam',
    designation: 'Data Annotator',
    category: 'Data Annotators',
    institution: 'Dept. of CSE, University of Chittagong',
    email: 'minhaj@std.cu.ac.bd',
    bio: 'Student researcher annotating domain ontology entities for agriculture and healthcare datasets.',
    image: '/team/minhaj.png',
    order: 11,
  },
  {
    id: 'team_arafat',
    name: 'Arafat Sheikh',
    designation: 'Data Annotator',
    category: 'Data Annotators',
    institution: 'Dept. of CSE, University of Chittagong',
    email: 'arafat.csecu@gmail.com',
    bio: 'Annotating Bangla domain text corpora and knowledge triples for LLM instruction tuning.',
    image: '/team/arafat.png',
    order: 12,
  },
  {
    id: 'team_kausik',
    name: 'Kausik Das',
    designation: 'Office Manager',
    category: 'Administrative Staff',
    institution: 'University of Chittagong',
    email: 'cukaushikdas@gmail.com',
    bio: 'Managing administrative operations, documentation, and coordination under HEAT-13211-CU ATF.',
    image: '/team/kausik.jpeg',
    order: 13,
  }
];

export const INITIAL_NEWS: NewsArticle[] = [
  {
    id: 'news_20',
    title: 'Professor Dr. Debasish Ghose from Kristiania University College, Norway visited our lab for collaboration',
    slug: 'prof-debasish-ghose-lab-visit',
    excerpt: 'Conducted an intensive quality paper writing workshop and strategic discussion on AI research roadmap.',
    content: 'Professor Dr. Debasish Ghose from Kristiania University College, Norway visited our lab for research collaboration and conducted an intensive quality paper writing workshop with graduate researchers.',
    category: 'workshop',
    publishDate: '2026-07-29',
    author: 'Admin Desk',
    status: 'published',
    featured: true,
    tags: ['Workshop', 'Collaboration', 'BDAI', 'Research', 'BIKE Lab'],
  },
  {
    id: 'news_19',
    title: 'e-Tenders invited on National e-GP System Portal for procurement of AI workstations under HEAT-13211-CU ATF',
    slug: 'e-tender-procurement-ai-workstations',
    excerpt: 'e-Tenders are invited on the National e-GP System Portal (www.eprocure.gov.bd) for supply and installation of AI workstations.',
    content: 'e-Tenders are invited on the National e-GP System Portal (https://www.eprocure.gov.bd) for the procurement of AI workstations under the HEAT-13211-CU ATF Sub-Project by the Department of Computer Science and Engineering, University of Chittagong, Chattogram.',
    category: 'announcement',
    publishDate: '2026-06-02',
    author: 'Procurement Officer',
    status: 'published',
    featured: true,
    tags: ['e-Tender', 'HEAT', 'Procurement', 'CSE CU', 'World Bank'],
  },
  {
    id: 'news_1',
    title: 'Md. Mosaddek Khan, Associate Professor of CSE, DU, presented on RAG-Driven Business Intelligence Platform Integration',
    slug: 'rag-driven-bi-presentation-du',
    excerpt: 'Enterprise Data for Real-Time Insight, Predictive, and Prescriptive Decision Analytics.',
    content: 'Md. Mosaddek Khan, Associate Professor of CSE, DU, presented: RAG-Driven Business Intelligence Platform Integration: Enterprise Data for Real-Time Insight, Predictive, and Prescriptive Decision Analytics.',
    category: 'event',
    publishDate: '2026-05-19',
    author: 'Editorial Desk',
    status: 'published',
    featured: false,
    tags: ['Seminar', 'BDAI', 'Business Intelligence'],
  },
  {
    id: 'news_2',
    title: 'Md Nesarul Hoque successfully presented his PhD Open Seminar-II',
    slug: 'nesarul-phd-open-seminar-2',
    excerpt: 'Successful second open seminar on cyberbullying detection and graph-based models.',
    content: 'Md Nesarul Hoque successfully presented his PhD Open Seminar-II at the Department of Computer Science and Engineering, University of Chittagong.',
    category: 'event',
    publishDate: '2026-05-14',
    author: 'BIKE Lab',
    status: 'published',
    featured: false,
    tags: ['Seminar', 'Cyberbullying', 'Security', 'PhD'],
  },
  {
    id: 'news_18',
    title: 'Professor Dr. Rudra Pratap Deb Nath Presented the Progress of the BDAI Sub-Project to World Bank, UGC, and HEAT Delegates',
    slug: 'world-bank-ugc-delegates-progress-presentation',
    excerpt: 'High-level presentation demonstrating sectoral knowledge graph breakthroughs and project milestones.',
    content: 'Professor Dr. Rudra Pratap Deb Nath Presented the Progress of the BDAI Sub-Project to the World Bank, UGC, and HEAT Delegates during their official visit.',
    category: 'news',
    publishDate: '2026-05-02',
    author: 'Communications',
    status: 'published',
    featured: true,
    tags: ['Presentation', 'BDAI', 'World Bank', 'UGC', 'HEAT'],
  },
  {
    id: 'news_3',
    title: 'Two OTM (Goods) e-Tenders under the BDAI project just published in the e-GP system',
    slug: 'two-otm-goods-tenders-published',
    excerpt: 'Invitations published on national procurement portal for laboratory equipment.',
    content: 'Two OTM (Goods) e-Tenders under the BDAI project just published in the e-GP system.',
    category: 'announcement',
    publishDate: '2026-02-10',
    author: 'Procurement Officer',
    status: 'published',
    featured: false,
    tags: ['Tender', 'BDAI', 'e-GP'],
  },
  {
    id: 'news_4',
    title: 'Director of BIKE Lab, Dr. Rudra Pratap Deb Nath Promoted to Professor at Department of CSE, University of Chittagong',
    slug: 'rudra-pratap-deb-nath-promoted-professor',
    excerpt: 'Heartiest congratulations to the director of BIKE Lab on promotion to Professor.',
    content: 'Director of BIKE Lab, Dr. Rudra Pratap Deb Nath Promoted to Professor at Department of CSE, University of Chittagong.',
    category: 'news',
    publishDate: '2026-01-18',
    author: 'BIKE Team',
    status: 'published',
    featured: true,
    tags: ['Director', 'Promotion', 'Professor', 'Achievement'],
  }
];

export const INITIAL_VACANCIES: Vacancy[] = [
  {
    id: 'vac_tender_1',
    title: 'Supply and installation of AI workstations (e-Tender Notice OTM Goods)',
    department: 'Department of Computer Science and Engineering',
    workPackage: 'HEAT-13211-CU ATF Sub-Project',
    type: 'e-Tender Notice (OTM Goods)',
    location: 'University of Chittagong, Chattogram',
    deadline: '2026-06-17',
    status: 'open',
    description: 'Procurement of high-performance GPU AI workstations under memo HEAT/CU/PIN13211/G-03.11/2025-2026 via National e-GP System Portal.',
    requirements: [
      'Submission strictly via National e-GP System Portal (www.eprocure.gov.bd)',
      'Valid Trade License and Tax Identification Number (TIN)',
      'Authorized OEM distributor partner certification for enterprise GPU hardware'
    ],
    applicantCount: 5,
  },
  {
    id: 'vac_phd_mphil',
    title: 'PhD and MPhil Research Fellowships under the BDAI project (HEAT)',
    department: 'BIKE Lab & CSE Department',
    workPackage: 'WP3 & WP5: Cross-Sectoral KGs & KG-RAG',
    type: 'Research Fellowship',
    location: 'University of Chittagong',
    deadline: '2026-08-30',
    status: 'open',
    description: 'Funded doctoral and masters positions for candidates pursuing state-of-the-art research in Knowledge Graph construction and LLM hallucination mitigation.',
    requirements: [
      'M.Sc. or B.Sc. in Computer Science & Engineering with excellent academic standing',
      'Strong programming proficiency in Python, PyTorch, and Neo4j',
      'Demonstrated enthusiasm for NLP and graph neural networks'
    ],
    applicantCount: 18,
  }
];

export const INITIAL_OBJECTIVES: ResearchObjective[] = [
  {
    id: 'OB1',
    title: 'Open Data Quality Measurement Framework',
    details: 'An Open data quality measurement framework for assessing completeness and freshness of national open datasets.',
    researcher: '(Masters-1)',
    sector: 'Data Governance',
    status: 'completed',
    progress: 100,
    deliverables: 3,
  },
  {
    id: 'OB2',
    title: 'SMART Data Ecosystem for Bangladesh',
    details: 'A full-fledged SMART data ecosystem tailored to Bangladesh data.',
    researcher: 'Research Associate-1',
    sector: 'SMART Ecosystem',
    status: 'in-progress',
    progress: 85,
    deliverables: 4,
  },
  {
    id: 'OB3',
    title: 'Cross-Sectoral Knowledge Graph Construction',
    details: 'Knowledge graph construction and optimization for different sectors: Socio-economic, Agriculture, Healthcare, Education, Tourism.',
    researcher: 'PhD-1 + Research Assistant-1',
    sector: 'Multi-Sectoral KGs',
    status: 'in-progress',
    progress: 75,
    deliverables: 5,
  },
  {
    id: 'OB4',
    title: 'Intra- and Inter-Sector Analytics',
    details: 'Enabling intra- and inter-sector analytics over knowledge graphs.',
    researcher: 'PhD-2 + Masters-2',
    sector: 'Analytics & Policy',
    status: 'in-progress',
    progress: 60,
    deliverables: 2,
  },
  {
    id: 'OB5',
    title: 'KG RAG: Grounding Context for LLMs',
    details: 'KG RAG: Leveraging KGs to provide the context to LLMs through retrieval augmented generation pipelines.',
    researcher: 'Masters-3',
    sector: 'AI Systems',
    status: 'in-progress',
    progress: 70,
    deliverables: 3,
  },
  {
    id: 'OB6',
    title: 'Explainability, Bias, and Fairness Validation',
    details: 'Ensuring explainability, bias and fairness, and validity of LLMs through KGs and vice versa.',
    researcher: 'PhD-3 + PostDoc-1',
    sector: 'Ethics & Safety',
    status: 'in-progress',
    progress: 45,
    deliverables: 2,
  },
  {
    id: 'OB7',
    title: 'askBDAI Conversational Intelligence',
    details: 'askBDAI: An AI-powered data-driven Q/A system exploiting graph pattern.',
    researcher: 'Masters-4 + Research Assistant-2',
    sector: 'Intelligent Interfaces',
    status: 'in-progress',
    progress: 55,
    deliverables: 2,
  },
  {
    id: 'OB8',
    title: 'Capacity Building & Collaborations',
    details: 'Capacity building through publications, workshops, collaboration, and engagement activities.',
    researcher: 'Research Team',
    sector: 'Capacity Building',
    status: 'in-progress',
    progress: 90,
    deliverables: 6,
  }
];

export const INITIAL_ACTIVITIES: ActivityLog[] = [
  {
    id: 'act_1',
    action: 'Published',
    entity: 'News Article',
    targetName: 'Prof. Dr. Debasish Ghose Lab Visit',
    timestamp: '2 hours ago',
    user: 'Miskatul Anwar',
  },
  {
    id: 'act_2',
    action: 'Updated Status',
    entity: 'e-Tender',
    targetName: 'Supply and installation of AI workstations',
    timestamp: '5 hours ago',
    user: 'Miskatul Anwar',
  },
  {
    id: 'act_3',
    action: 'Updated Milestone',
    entity: 'Objective',
    targetName: 'OB2: SMART data ecosystem (85%)',
    timestamp: 'Yesterday',
    user: 'Prof. Dr. Rudra Pratap Deb Nath',
  },
  {
    id: 'act_4',
    action: 'Added',
    entity: 'Team Member',
    targetName: 'Atik Ishrak (Research Assistant)',
    timestamp: '2 days ago',
    user: 'Miskatul Anwar',
  }
];

export const INITIAL_TOOLS: Tool[] = [
  {
    id: 'setlbi',
    title: 'SETLBI',
    subtitle: 'An Integrated Platform for Semantic Business Intelligence',
    description: 'A tool that combines Semantic Web and Business Intelligence technologies to define, process, integrate, and query semantic data.',
    abstract: 'With the growing popularity of Semantic Web technologies, more and more organizations natively manage data using Semantic Web standards, in particular RDF. This development gives rise to new requirements for Business Intelligence tools to enable analyses in the style of On-Line Analytical Processing (OLAP) over RDF data. SETLBI brings together the Semantic Web and Business Intelligence technologies across target definition, source to target mappings, source extraction, data transformation, and target population.',
    paperUrl: 'https://extbi.cs.aau.dk/SETLBI/SETLBI.pdf',
    sourceUrl: 'https://github.com/bi-setl/SETL',
    platformUrl: 'https://extbi.cs.aau.dk/SETLBI/index.php',
    videoUrl: 'https://www.youtube.com/embed/9-a4MVHqZow',
    authors: 'Rudra Pratap Deb Nath, Katja Hose, Torben Bach Pedersen, Oscar Romero, and Amrit Bhattacharjee',
    features: [
      'Semantic integration',
      'RDF + OLAP workflows',
      'End-to-end data pipeline'
    ],
    order: 1,
    badge: 'Tool Showcase'
  }
];
